# .github/workflows/release.yml
name: Create Release

on:
  push:
    tags:
      - 'v*' # This workflow runs when a tag like v1.0.0 is pushed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            New release based on tag ${{ github.ref }}. See the changelog for details.
          draft: false
          prerelease: false
